### ISSUE TITLE
-C option doesn't work

### ISSUE THREAD

**Issue by jsummers** [vapier/ncompress#26]
The README.md file says you can use -C to create files that are "compatible with compress 2.0". But as far as I can tell, you can't. All -C does is change a bit in the header, asserting that the file uses the 2.0 format. But it doesn't use that format, so the file is invalid. It can't be decompressed by ncompress, or anything else I've tried.

```
$ echo "aaaaaaaaaaaaaaaa" | compress -C | compress -d
insize:8 posbits:9 inbuf:61 02 0A 1C 48 (1)
uncompress: corrupt input
```

Expected results: Either the feature should be implemented, or -C should fail with an error message, with the README file updated accordingly.

(Using the 4.2.4 branch, but I don't think it matters.)

**Comment by vapier** [comment]
i spent a lot of time today digging through dark archives of the internet to try and recreate the history of the compress project.  i've come to the opinion that support for creating compress-2.0 files isn't important and it should be dropped.

the relevant history:
* 30 Aug 1984: compress-2.0 is posted to net.sources
* 04 Sep 1984: news 2.10.2 is posted to net.sources (bundles compress-1.6 which uses same format as 2.0 i believe)
* 03 Jan 1985: compress-3.0 is posted to mod.sources.  this changes output format to not be backwards compat, but includes -C option to produce older format.
* 01 Aug 1985: compress-4.0 is posted to mod.sources.  this is the last "official" version and what everyone forks from.
* 21 May 1986: news 2.10.3 is posted to net.sources (includes compress-4.0)

at the time, backwards compat was important due to the slow (and manual) code update process, and that the news project (read: usenet) was important to keep compatibility with existing installs.

however, i doubt anyone is running the news program anymore, let alone versions that predate 2.10.3 (i.e. May 1986).  similarly for compress, i doubt anyone is running pre-compress-4.0 code anywhere.  3 decades is plenty of time to upgrade software :P.

the important thing here is that old compress files are still supported by the latest ncompress versions, we just won't be able to produce the old format.  i need to track down a few more old releases to try and stitch the history together to see when the -C option broke (prob more for curiosity at this point).

**Comment by jsummers** [comment]
I can only speak for myself, but I agree that it's hard to believe anyone still needs the -C feature. Except maybe if you want to make some old-format files to test 'uncompress' software, which is what I was trying to do.

At the risk of giving this more attention than it deserves...

I got an ancient 4.0 version of compress.c compiled, and -C seems to work, and produces files that can be decompressed by it, and by ncompress v4.2.4. So that's good. I haven't looked at any older versions, and I won't speculate about which versions, if any, actually used this format by default. But it's at least the de facto standard "old format".

What I think is odd about it is that (as a knock-on effect of code #256 being available) it has 63 bits of padding between the 9-bit and the 10-bit codes. I could be wrong, but I think that's the only case in either version where padding is needed at the point of a code size increment. In all other cases, the number of codes will necessarily be a multiple of 8 at that point, so no padding is needed.

Don't trust me on this, but if the -C option is definitively removed, it's possible that the compress() code that does the code size increment could be simplified.

**Comment by vapier** [comment]
i spent more time digging through history and resurrecting old code.  here's what i did:
* build compress-2.0 and compress a file
* build compress-4.0 and compress same file using -C
* hash the outputs and show they're the same
* build compress-4.1 (from Dave Mack) and compress same file using -C
* hash the outputs and show they're the same
* build compress-4.1p1 (from Dave Mack) and compress same file using -C
* hash the outputs and show they're the same
* build ncompress-4.2.3 (from Peter Jannesen) and compress same file using -C
* hash the outputs and show they're *not* the same
* build ncompress-4.2.4.6 (my latest release) and compress same file using -C
* output of 4.2.4.6 matches 4.2.3

so it looks like the bug was introduced during Peter's development of compress-4.2 based on Dave's compress-4.1p1.  i can't find anything earlier than 4.2.3 unfortunately to bisect further.

this rabbit hole has forced me to dig through the history (now available on the [project's homepage](https://vapier.github.io/ncompress/)), and allowed me to integrate those early/ancient releases into the git history.  i'm going to rewrite the master branch here (which hasn't really been used thus far) to integrate all the public releases starting from the first one at v1.4.

so that means, for people who want to produce v2.0 compatible outputs, they can simply grab the older releases here.  that should be good enough for this edge case.
