### ISSUE TITLE
compression with 9 bits don't work

### ISSUE THREAD

**Issue by trek00** [vapier/ncompress#5]
it simply doesn't work (no 8-codes block flush after the clear code?):
$ compress -cb9 /usr/bin/compress >/tmp/test.Z
$ compress -dc /tmp/test.Z
insize:7901 posbits:0 inbuf:00 0A F7 23 CC (0)
uncompress: corrupt input
$ gzip -tv /tmp/test.Z
gzip: /tmp/correct.Z: corrupt input.

and it is not working for a long time (at least 12 years):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=220820

the debian proposed patch (using at least 10 bits) would break the Single UNIX Specification, Version 4 (IEEE Std 1003.1) as 9 <= bits <= 14:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/compress.html

if the bug cannot be resolved, a note should be added, like the one present in the debian package readme:
"If you create files using -b9 (maxbits of 9), your file is probably corrupted, and you will only be able to recover parts of it."

ciao!

**Comment by trek00** [comment]
my previous sentence was incorrect: the debian proposed patch would NOT break the SUSv4 as "the format of compressed files is unspecified", so if the -b9 option is accepted (even if ignored) the conformance is not affected

**Comment by andrew-aladev** [comment]
[gzip unlzw](https://github.com/Distrotech/gzip/blob/distrotech-gzip/unlzw.c) is just a bit modified decompressor from lzw.

The main problem is cipher in compress:

```
boff = outbits = (outbits-1)+((n_bits<<3)-((outbits-boff-1+(n_bits<<3))%(n_bits<<3)));
```

And it's variant in decompress:

```
posbits = ((posbits-1) + ((n_bits<<3) - (posbits-1+(n_bits<<3))%(n_bits<<3)));
```

There is no comments, no git history available. It is `a fast, simple LZW file compressor` =)

![download](https://user-images.githubusercontent.com/941925/49255733-efe8e480-f43d-11e8-846c-33fdddf18267.jpeg)

I can't decode this "code" bomb. It looks like some alien tried to write remainder, but failed. I am writing it in [the following way](https://github.com/andrew-aladev/lzws/blob/master/src/compressor/write.c#L25-L38). But my compressor is not ready yet. I have to be compatible with ncompress, so this bomd should be demined.

**Comment by andrew-aladev** [comment]
Patch provided by debian maintainer is just a strange dance around code bits. Code bits has nothing to do with this issue. The problem is write manipulations with `posbits`:

```
posbits = 3<<3;
posbits = 0;
posbits = ((posbits-1) + ((n_bits<<3) - (posbits-1+(n_bits<<3))%(n_bits<<3))); // worst nightmare
input(inbuf,posbits,code,n_bits,bitmask);
posbits -= n_bits;
```

Unfortunately we have no ncompress version 4.1. This version was without this "optimization" and we can understand how to throw out this "formula" back to the hell.

**Comment by andrew-aladev** [comment]
Finally I've restored the reason why our grandfathers were using `n_bits << 3` in 1985.

```
if (offset == (n_bits << 3)) {
  bp = buf;
  bits = n_bits;
  bytes_out += bits;
  do
    putchar(*bp++);
  while (--bits);
  offset = 0;
}
```

`offset == (n_bits << 3)` means `destination remainder is 100% empty`.

Example: we are writing 9 bit codes, destination remainder will be empty when `9 * x % 8 = 0` => `x = 8, 16, ...`, but for 14 bit codes it is not so accurate: `14 * x % 8 = 0` => `x = 4, 8, ...`. This method is dummy, but reliable.

It means that we have some kind of `n_bits * 8` virtual destination pre-buffer and we are flushing it into main buffer only in special cases.

More obvious way is to write bytes that has already been completed. For example [libtiff](http://www.amc.anl.gov/anlsoftwarelibrary/02-mmslib/IMAG/TIFFFOLD/LIBTIFF/tiff_lzw.c).

```
/*
* Flush buffer if code doesn't fit.
*/
if (r_off + bits > sp->lzw_bitsize) {
  /*
  * Calculate the number of full bytes that can be
  * written and save anything else for the next write.
  */
```

This solution is completely different from `virtual destination pre-buffer` and obvious, moreover it is well documented. Nobody will suffer on reverse engineering it in libtiff.

-----

Does `boff` mean `buffer offset`? It does not, it is just completely wrong abbreviation, which produces pain for all who tries to read it. It can be named as `virtual destination pre-buffer bit offset`.

To be continued.

**Comment by andrew-aladev** [comment]
I've found the reason of this issue.

`ncompress 4.2`:
```
boff = outbits = (3<<3);
bytes_out = 0;
```

`ncompress 4.0`:
```
offset = 0;
bytes_out = 3; /* includes 3-byte header mojo */
```

3 header bytes provides 24 bit offset. It breaks alignment logic with 9 bits. There should not be any offset for alignment calculation.

**Comment by trek00** [comment]
wow, you have done a wonderful analysis, congratulations! I should try to fix my compress shell script with your findings!

**Comment by andrew-aladev** [comment]
I've downloaded a bunch of `tar.Z` files from internet. I have to say that alignment byte won't guaranteed to be zero. There was an implementation of lzw that writes alignment bytes from buffer without initializing them. You can reproduce it with `https://archive.apache.org/dist/httpd/httpd-2.1.3-beta.tar.Z`. It has non zero alignment bits. So we have just to ignore alignment bits during reading.

**Comment by ShimmerFairy** [comment]
I just ran into this problem, but what's weird is that reading the file with `less` (which tends to do stuff like automatically decompress files) and redirecting the output to another file seems to work fine, no complaints about corrupt data or anything.

**Comment by N-R-K** [comment]
> I've added a paragraph into [wikipedia](https://en.wikipedia.org/wiki/Compress).

@andrew-aladev I was writing a lzw decompressor (for education mostly) and wanted to handle reset codes but run into the alignment issue. I'm not entirely clear on how it works, can you answer some of my questions?

> Each group (except last) should be aligned by amount of bits multiplied by 8 and right padded with zeroes.

This padding only applies after emitting a reset code, right? Because currently my decoder increases the number of bits when dictionary size increases without doing any alignment. And it seems to be working fine.

```c
	if (cursym == (1 << bits) && bits < maxbits) {
		++bits;
	}
```

For reset code, I track the number of bits that have been read. And after encountering a reset code, I keep reading (i.e ignoring) bits until the number of bits read is divisible by `bits * 8`:


```c
	int code = bitread(bi, bits);
	bitsread += bits;
	if (code == 256 && blockmode) {
		while (bitsread % (8 * bits) != 0) {
			bitread(bi, 1);
			bitsread += 1;
		}
		// reset state...
	}
```

Unfortunately this doesn't seem to work reliably. Did I misunderstand how the alignment is supposed to work?

**Comment by andrew-aladjev** [comment]
Hello @N-R-K, I can explain a bit about how it works. Output group means several values of the same bit length. For example, you want to output 10 values with 9-bit length, than 20 values with 10-bit length, 30 values with 11-bit length, etc.

A clear (reset) code means you want to reset the internal compressor/decompressor state. It means you want to reset the dictionary and current bit length. It happens when dictionary is full or the compression ratio becomes too bad. There is a static gap for ratio calculation: `compress` will read at least 10000 before checking the ratio value.

> This padding only applies after emitting a reset code

You can actually not apply any padding; it is required only for compatibility with the `tar.Z` historical format. `lzws` has a special mode [--unaligned-bit-groups](https://github.com/andrew-aladev/lzws/blob/1e97fd52630bf4da1ba8bfaa4e8e35495413b1da/man/lzws.1.txt#L56) that allows to drop this compatibility.

If you want to be compatible with the `tar.Z` historical format, you need to align any output group, which means you need to apply right padding at the end of each group except the last one. Last group means the last group before the reset code or at EOF.

Values alignment is not the only one problem for `tar.Z` format, please read more about LSB and MSB here [output_compatibility.txt](https://github.com/andrew-aladev/lzws/blob/master/doc/output_compatibility.txt).

**Comment by fadden** [comment]
I poked at this a little.  In standard "block mode", the code size expansions happen to land on 8-code boundaries every time, so you can generally read the compressed data as a continuous stream of codes without regard to alignment considerations.  This works until you hit a CLEAR code, which changes the code width without regard to file position.

This is why the `compress` implementation in `unar` is able to use a generic LZW implementation, right up to the point where a [table clear happens](https://github.com/ashang/unar/blob/473488cc612c3f47e1c76f9baf92d268db259dc1/XADMaster/XADCompressHandle.m#L45).

If you generate a compressed file with block mode disabled, by passing the `-C` flag to compress v4.0, the CLEAR code is not reserved.  The code table therefore has one additional value available.  This throws everything off by one, and the 8-code block alignment becomes significant at the first code size change.  I confirmed that `unar` fails to handle such files:
```
% unar test.Z
test.Z: Compress
  test... Failed! (Error on decrunching)
Extraction to current directory failed! (1 file failed.)
```
Other utilities on my Linux system, such as (N)compress 4.2.4.6 and gzip v1.10, handled the same file just fine.

Interesting stuff.  If it weren't for the notes in the wikipedia page, I probably wouldn't have been aware of it.
